'------------------------------------------------------------------------------
' <auto-generated>
'     Este código fue generado por una herramienta.
'     Versión de runtime:4.0.30319.42000
'
'     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
'     se vuelve a generar el código.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'StronglyTypedResourceBuilder generó automáticamente esta clase
    'a través de una herramienta como ResGen o Visual Studio.
    'Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    'con la opción /str o recompile su proyecto de VS.
    '''<summary>
    '''  Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("EmailSearcher.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        '''  búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a aaa
        '''aarp
        '''abb
        '''abbott
        '''abbvie
        '''abc
        '''able
        '''abogado
        '''abudhabi
        '''ac
        '''academy
        '''accenture
        '''accountant
        '''accountants
        '''aco
        '''actor
        '''ad
        '''ads
        '''adult
        '''ae
        '''aeg
        '''aero
        '''aetna
        '''af
        '''afl
        '''africa
        '''ag
        '''agakhan
        '''agency
        '''ai
        '''aig
        '''airbus
        '''airforce
        '''airtel
        '''akdn
        '''al
        '''alibaba
        '''alipay
        '''allfinanz
        '''allstate
        '''ally
        '''alsace
        '''alstom
        '''am
        '''amazon
        '''americanexpress
        '''americanfamily
        '''amex
        '''amfam
        '''amica
        '''amsterdam
        '''analytics
        '''android
        '''anquan
        '''anz
        '''ao
        '''aol
        '''apartments
        '''app
        '''apple
        '''aq
        '''aquarelle
        '''ar
        '''arab
        '''aramco
        '''archi
        '''army
        '''arpa
        '''art
        '''arte
        '''as
        '''asda
        '''asia
        '''associates
        '''at
        '''athleta
        '''attorney
        '''au
        '''auction
        '''audi
        '''audible
        '''audio [resto de la cadena truncado]&quot;;.
        '''</summary>
        Friend ReadOnly Property domains() As String
            Get
                Return ResourceManager.GetString("domains", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Byte[].
        '''</summary>
        Friend ReadOnly Property font() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("font", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
    End Module
End Namespace
